export const initialReceipes = [
  {
    id: '3a9979a2-0e9b-4f7c-9b13-03abbc5d482c',
    title: 'Spaghetti Bolognese',
    cuisine_type: 'Italian',
    ingredients: [
      '500g spaghetti',
      '400g ground beef',
      '1 onion, chopped',
      '2 cloves of garlic, minced',
      '400g canned diced tomatoes',
      '2 tablespoons tomato paste',
      '1 teaspoon dried oregano',
      '1 teaspoon dried basil',
      'Salt and pepper to taste',
      'Grated Parmesan cheese, for serving',
    ],
    instructions: [
      'Cook the spaghetti according to the package instructions. Drain and set aside.',
      'In a large skillet, brown the ground beef over medium heat until cooked through. Drain any excess fat.',
      'Add the chopped onion and minced garlic to the skillet with the cooked beef. Sauté until the onion is translucent.',
      'Stir in the canned diced tomatoes, tomato paste, dried oregano, dried basil, salt, and pepper. Simmer for 20 minutes, stirring occasionally.',
      'Serve the Bolognese sauce over the cooked spaghetti. Sprinkle with grated Parmesan cheese.',
      'Enjoy!',
    ],
    image_link:
      'https://www.ocado.com/cmscontent/recipe_image_large/33362787.png',
  },
  {
    id: '723f68e9-7f84-4f0f-9a92-2e9a0fb64eae',
    title: 'Chicken Tikka Masala',
    cuisine_type: 'Indian',
    ingredients: [
      '500g boneless chicken, cut into cubes',
      '1 cup plain yogurt',
      '2 tablespoons lemon juice',
      '2 teaspoons ground cumin',
      '2 teaspoons ground coriander',
      '1 teaspoon ground turmeric',
      '1 teaspoon chili powder',
      '1 teaspoon garam masala',
      '2 tablespoons vegetable oil',
      '1 onion, finely chopped',
      '2 cloves of garlic, minced',
      '1-inch piece of ginger, grated',
      '1 cup canned tomato puree',
      '1 cup heavy cream',
      'Salt to taste',
      'Chopped fresh cilantro, for garnish',
    ],
    instructions: [
      'In a bowl, mix the yogurt, lemon juice, ground cumin, ground coriander, ground turmeric, chili powder, and garam masala to make the marinade.',
      'Add the chicken cubes to the marinade, ensuring they are well coated. Let it marinate for at least 1 hour, or overnight in the refrigerator for better flavor.',
      'Heat the vegetable oil in a large skillet over medium heat. Add the chopped onion and sauté until golden brown.',
      'Add the minced garlic and grated ginger to the skillet. Sauté for an additional minute.',
      'Stir in the canned tomato puree and heavy cream. Simmer for 10 minutes, or until the sauce thickens.',
      'Add the marinated chicken to the skillet. Cook until the chicken is cooked through, about 10-15 minutes.',
      'Season with salt to taste. Garnish with chopped fresh cilantro.',
      'Serve the Chicken Tikka Masala with steamed rice or naan bread.',
      'Enjoy!',
    ],
    image_link:
      'https://www.indianhealthyrecipes.com/wp-content/uploads/2022/06/chicken-tikka-masala.jpg',
  },
  {
    id: 'de3c0d45-6920-4d5c-8d4f-3105c136a5d9',
    title: 'Classic Cheeseburger',
    cuisine_type: 'American',
    ingredients: [
      '500g ground beef',
      '4 hamburger buns',
      '4 slices of cheese',
      'Lettuce leaves',
      'Sliced tomatoes',
      'Sliced onions',
      'Ketchup',
      'Mustard',
      'Salt and pepper to taste',
    ],
    instructions: [
      'Divide the ground beef into four equal portions and shape them into patties.',
      'Season the patties with salt and pepper.',
      'Preheat a grill or skillet over medium-high heat.',
      'Cook the patties for about 4-5 minutes on each side, or until they reach your desired level of doneness.',
      'During the last minute of cooking, place a slice of cheese on each patty to melt.',
      'Toast the hamburger buns on the grill or skillet for a minute.',
      'Assemble the burgers by placing a patty on the bottom half of each bun.',
      'Top with lettuce leaves, sliced tomatoes, and sliced onions.',
      'Spread ketchup and mustard on the top half of the buns.',
      'Cover the burgers with the top half of the buns.',
      'Serve the classic cheeseburgers with your favorite sides.',
      'Enjoy!',
    ],
    image_link:
      'https://assets.epicurious.com/photos/5c745a108918ee7ab68daf79/1:1/w_2560%2Cc_limit/Smashburger-recipe-120219.jpg',
  },
  {
    id: '5a051e27-b26f-4e43-a4d5-91ce02ff07f7',
    title: 'Caprese Salad',
    cuisine_type: 'Italian',
    ingredients: [
      '4 ripe tomatoes, sliced',
      '250g fresh mozzarella cheese, sliced',
      'Fresh basil leaves',
      'Extra-virgin olive oil',
      'Balsamic glaze',
      'Salt and pepper to taste',
    ],
    instructions: [
      'Arrange the tomato and mozzarella slices on a platter, alternating them.',
      'Tuck fresh basil leaves between the tomato and mozzarella slices.',
      'Drizzle extra-virgin olive oil over the salad.',
      'Drizzle balsamic glaze on top.',
      'Season with salt and pepper to taste.',
      'Serve the Caprese salad as a side dish or appetizer.',
      'Enjoy!',
    ],
    image_link:
      'https://images.immediate.co.uk/production/volatile/sites/30/2022/05/Caprese-salad-8f218a3.png',
  },
  {
    id: '04b1f49c-8552-4e19-b6e7-365e346e65f8',
    title: 'Chicken Stir-Fry',
    cuisine_type: 'Asian',
    ingredients: [
      '500g boneless, skinless chicken breasts, sliced',
      '2 tablespoons soy sauce',
      '1 tablespoon oyster sauce',
      '1 tablespoon hoisin sauce',
      '1 tablespoon cornstarch',
      '2 tablespoons vegetable oil',
      '2 cloves of garlic, minced',
      '1-inch piece of ginger, grated',
      '1 onion, sliced',
      '1 bell pepper, sliced',
      '1 carrot, julienned',
      '2 cups broccoli florets',
      'Salt and pepper to taste',
    ],
    instructions: [
      'In a bowl, whisk together soy sauce, oyster sauce, hoisin sauce, and cornstarch to make the sauce.',
      'Heat vegetable oil in a large skillet or wok over high heat.',
      'Add minced garlic and grated ginger to the skillet. Stir-fry for a minute.',
      'Add sliced chicken to the skillet. Stir-fry until the chicken is cooked through.',
      'Add sliced onion, bell pepper, julienned carrot, and broccoli florets to the skillet. Stir-fry for a few minutes until the vegetables are tender-crisp.',
      'Pour the sauce over the stir-fry and toss to coat evenly.',
      'Season with salt and pepper to taste.',
      'Continue to stir-fry for another minute.',
      'Serve the chicken stir-fry over steamed rice or noodles.',
      'Enjoy!',
    ],
    image_link:
      'https://images.immediate.co.uk/production/volatile/sites/30/2020/08/recipe-image-legacy-id-14362_11-f85caa7.jpg?quality=90&resize=440,400',
  },
  {
    id: '209a327a-49f6-4f48-9f8f-049e3e685a0a',
    title: 'Chocolate Chip Cookies',
    cuisine_type: 'Dessert',
    ingredients: [
      '1 cup butter, softened',
      '1 cup granulated sugar',
      '1 cup brown sugar',
      '2 large eggs',
      '1 teaspoon vanilla extract',
      '3 cups all-purpose flour',
      '1 teaspoon baking soda',
      '1/2 teaspoon salt',
      '2 cups chocolate chips',
    ],
    instructions: [
      'Preheat the oven to 375°F (190°C).',
      'In a large bowl, cream together the softened butter, granulated sugar, and brown sugar until smooth.',
      'Beat in the eggs one at a time, then stir in the vanilla extract.',
      'In a separate bowl, whisk together the flour, baking soda, and salt.',
      'Gradually add the dry ingredients to the butter mixture, mixing well after each addition.',
      'Fold in the chocolate chips.',
      'Drop rounded tablespoonfuls of dough onto ungreased baking sheets.',
      'Bake for 8-10 minutes, or until golden brown around the edges.',
      'Allow the cookies to cool on the baking sheets for a few minutes, then transfer them to wire racks to cool completely.',
      'Enjoy the delicious chocolate chip cookies!',
    ],
    image_link:
      'https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/62298.jpg',
  },
];
